spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/arkadiusz/Pulpit/kurs springboot/todo-db'
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate






