spring:
  h2.console:
      enabled: true
      path: '/console'
  datasource:
      url: 'jdbc:h2:file:/home/arkadiusz/Pulpit/kurs springboot/todo-db'








#tak wygladaloby to gdyby dac application.properties
#spring.h2.console.enabled=true
#spring.h2.console.path=/console
#spring.datasource.url=jdbc:h2:file:/home/arkadiusz/Pulpit/kurs springboot/todo-db

